# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "prod-colinreddig-dot-com-terraform-state-management"
    encrypt      = true
    key          = "artifacts/terraform.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
